FROM python:3.11-slim

ENV PIP_DEFAULT_TIMEOUT=120 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_RETRIES=5

RUN pip install --no-cache-dir \
    mlflow==2.10.0 \
    psycopg2-binary==2.9.9

CMD ["mlflow", "server", \
     "--backend-store-uri", "postgresql://postgres:postgres@postgres:5432/mlflow", \
     "--default-artifact-root", "/mlflow/artifacts", \
     "--host", "0.0.0.0", \
     "--port", "5000"]
