apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: credit_scoring
    user: ml_user
    isDefault: true
    secureJsonData:
      password: ml_password
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      maxOpenConns: 5
      maxIdleConns: 5
