-- Создание пользователя и баз данных
CREATE USER ml_user WITH PASSWORD 'ml_password';
CREATE USER airflow WITH PASSWORD 'airflow';

CREATE DATABASE credit_scoring OWNER ml_user;
CREATE DATABASE airflow OWNER airflow;
CREATE DATABASE mlflow OWNER postgres;

-- Подключаемся к credit_scoring
\c credit_scoring;

-- Схемы
CREATE SCHEMA IF NOT EXISTS raw AUTHORIZATION ml_user;
CREATE SCHEMA IF NOT EXISTS features AUTHORIZATION ml_user;
CREATE SCHEMA IF NOT EXISTS models AUTHORIZATION ml_user;
CREATE SCHEMA IF NOT EXISTS predictions AUTHORIZATION ml_user;
CREATE SCHEMA IF NOT EXISTS monitoring AUTHORIZATION ml_user;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA raw TO ml_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA features TO ml_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA models TO ml_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA predictions TO ml_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA monitoring TO ml_user;