-- sql/01_init_schema.sql

CREATE USER ml_user WITH PASSWORD 'ml_password';
CREATE USER airflow WITH PASSWORD 'airflow';

CREATE DATABASE credit_scoring OWNER ml_user;
CREATE DATABASE airflow OWNER airflow;
CREATE DATABASE mlflow OWNER postgres;

\c credit_scoring;

CREATE SCHEMA IF NOT EXISTS raw AUTHORIZATION ml_user;
CREATE SCHEMA IF NOT EXISTS features AUTHORIZATION ml_user;
CREATE SCHEMA IF NOT EXISTS models AUTHORIZATION ml_user;
CREATE SCHEMA IF NOT EXISTS predictions AUTHORIZATION ml_user;
CREATE SCHEMA IF NOT EXISTS monitoring AUTHORIZATION ml_user;

-- Права на существующие объекты
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA raw TO ml_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA features TO ml_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA models TO ml_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA predictions TO ml_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA monitoring TO ml_user;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA raw TO ml_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA features TO ml_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA models TO ml_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA predictions TO ml_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA monitoring TO ml_user;

-- КЛЮЧЕВОЕ: права на БУДУЩИЕ объекты
ALTER DEFAULT PRIVILEGES IN SCHEMA raw
    GRANT ALL PRIVILEGES ON TABLES TO ml_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA features
    GRANT ALL PRIVILEGES ON TABLES TO ml_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA models
    GRANT ALL PRIVILEGES ON TABLES TO ml_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA predictions
    GRANT ALL PRIVILEGES ON TABLES TO ml_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA monitoring
    GRANT ALL PRIVILEGES ON TABLES TO ml_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA raw
    GRANT ALL PRIVILEGES ON SEQUENCES TO ml_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA features
    GRANT ALL PRIVILEGES ON SEQUENCES TO ml_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA models
    GRANT ALL PRIVILEGES ON SEQUENCES TO ml_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA predictions
    GRANT ALL PRIVILEGES ON SEQUENCES TO ml_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA monitoring
    GRANT ALL PRIVILEGES ON SEQUENCES TO ml_user;