-- Create roles and databases (runs as postgres superuser on first boot)
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'ml_user') THEN
        CREATE USER ml_user WITH PASSWORD 'ml_password';
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'airflow') THEN
        CREATE USER airflow WITH PASSWORD 'airflow';
    END IF;
END
$$;

SELECT 'CREATE DATABASE credit_scoring OWNER ml_user'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'credit_scoring')\gexec

SELECT 'CREATE DATABASE airflow OWNER airflow'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'airflow')\gexec

SELECT 'CREATE DATABASE mlflow OWNER postgres'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'mlflow')\gexec

\c credit_scoring

CREATE SCHEMA IF NOT EXISTS raw AUTHORIZATION ml_user;
CREATE SCHEMA IF NOT EXISTS features AUTHORIZATION ml_user;
CREATE SCHEMA IF NOT EXISTS models AUTHORIZATION ml_user;
CREATE SCHEMA IF NOT EXISTS predictions AUTHORIZATION ml_user;
CREATE SCHEMA IF NOT EXISTS monitoring AUTHORIZATION ml_user;

GRANT ALL PRIVILEGES ON SCHEMA raw TO ml_user;
GRANT ALL PRIVILEGES ON SCHEMA features TO ml_user;
GRANT ALL PRIVILEGES ON SCHEMA models TO ml_user;
GRANT ALL PRIVILEGES ON SCHEMA predictions TO ml_user;
GRANT ALL PRIVILEGES ON SCHEMA monitoring TO ml_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA raw
    GRANT ALL ON TABLES TO ml_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA features
    GRANT ALL ON TABLES TO ml_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA models
    GRANT ALL ON TABLES TO ml_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA predictions
    GRANT ALL ON TABLES TO ml_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA monitoring
    GRANT ALL ON TABLES TO ml_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA raw
    GRANT ALL ON SEQUENCES TO ml_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA features
    GRANT ALL ON SEQUENCES TO ml_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA predictions
    GRANT ALL ON SEQUENCES TO ml_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA monitoring
    GRANT ALL ON SEQUENCES TO ml_user;


-- Ensure airflow role can use its database
GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;
GRANT ALL PRIVILEGES ON DATABASE credit_scoring TO ml_user;
GRANT ALL PRIVILEGES ON DATABASE mlflow TO postgres;
